// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type User struct {
	ID             int32
	FirstName      string
	LastName       string
	Username       string
	HashedPassword string
}
